version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: nebula_task_db
    environment:
      POSTGRES_USER: api_dev_user
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: nebula_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nebula_task_app
    ports:
      - "3000:3000"
      - "9229:9229"       # Debugger port for Node.js
    depends_on:
      - postgres
    env_file:
      - .development.env
    environment:
      DATABASE_HOST: postgres
    volumes:
      - .:/usr/src/app
    command: npm run start:debug

volumes:
  db_data:
